const ClientInputData = [
    {
        type: 'text',
        name: 'Client Name',
        label: 'Client Name',
        id: 'Client_Name',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'Number',
        name: 'Client Code',
        label: 'Client Code',
        id: 'Client_Code',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'text',
        name: 'Contact Pereson Name',
        label: 'Contact Pereson Name',
        id: 'Contact_Pereson_Name',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'Number',
        name: 'Phone Number',
        label: 'Phone Number',
        id: 'Phone_Number',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'text',
        name: 'Email',
        label: 'Email',
        id: 'Email',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'text',
        name: 'Address',
        label: 'Address',
        id: 'Address',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'select',
        name: 'Country',
        label: 'Select Country',
        id: 'Country',
        SelectProps:"{{native: false,}}",
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,  
        options:[{
            value: 'India',
            label: 'India',
          },
          {
            value: 'Turkmenistan',
            label: 'Turkmenistan',
          },
          {
            value: 'Tunisia',
            label: 'Tunisia ',
          },
        ]
    },
    {
        type: 'select',
        name: 'State',
        label: 'Select State',
        id: 'State',
        SelectProps:"{{native: false,}}",
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
        options:[{
            value: 'Andhra Pradesh',
            label: 'Andhra Pradesh',
          },
          {
            value: 'Arunachal Pradesh',
            label: 'Arunachal Pradesh',
          },
          {
            value: 'Madhya Pradesh',
            label: 'Madhya Pradesh',
          },
        ]
    },
    {
        type: 'select',
        name: 'City',
        label: 'Select City',
        id: 'City',
        SelectProps:"{{native: false,}}",
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
        options:[{
            value: 'Bhopal',
            label: 'Bhopal',
          },
          {
            value: 'Inodre',
            label: 'Inodre',
          },
          {
            value: 'Dewas',
            label: 'Dewas',
          },
        ]
    },
    {
        type: 'Number',
        name: 'Pin Code',
        label: 'Pin Code',
        id: 'Pin_Code',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
        type: 'file',
        name: 'Client Logo',
        label: 'Client Logo',
        id: 'Client_Logo',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
        
    },
    {
        type: 'password',
        name: 'Client Password',
        label: 'Client Password',
        id: 'Client_Password',
        value: '',
        hasError: false,
        disabled: false,
        isRequired: false,
    },
    {
      type: 'radio',
      name: 'Question feedback',
      label: 'Question feedback',
      id: 'Question_feedback',
      value: '',
      hasError: false,
      disabled: false,
      isRequired: false,
      options:[{
        value: 'Yes',
        label: 'Yes',
        id:'Yes',
      },
      {
        value: 'no',
        label: 'no',
        id:'Yes',
      },
    ],
  },
]
export default ClientInputData;

    

